"""initial_schema

Revision ID: bb40b14047bd
Revises: 
Create Date: 2026-09-14 12:10:53.191571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy.vector


revision: str = 'bb40b14047bd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resumeiq_resume_id', sa.String(), nullable=True),
    sa.Column('puter_file_path', sa.String(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('resumeiq_audit_json', sa.JSON(), nullable=True),
    sa.Column('profile', sa.JSON(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('github_url', sa.String(), nullable=True),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('current_title', sa.String(), nullable=True),
    sa.Column('years_experience', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mandate_id', sa.UUID(), nullable=True),
    sa.Column('candidate_id', sa.UUID(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('embedding_model', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mandates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recruiter_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('raw_jd', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('job_requirements', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mandates_recruiter_id'), 'mandates', ['recruiter_id'], unique=False)
    op.create_table('analysis_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mandate_id', sa.UUID(), nullable=True),
    sa.Column('run_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('agent1_status', sa.String(), nullable=True),
    sa.Column('agent2_status', sa.String(), nullable=True),
    sa.Column('agent3_status', sa.String(), nullable=True),
    sa.Column('github_status', sa.String(), nullable=True),
    sa.Column('agent4_status', sa.String(), nullable=True),
    sa.Column('agent5_status', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mandate_id'], ['mandates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate_evaluations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mandate_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('verification_result', sa.JSON(), nullable=True),
    sa.Column('tech_coverage_pct', sa.Float(), nullable=True),
    sa.Column('github_analysis', sa.JSON(), nullable=True),
    sa.Column('github_verified', sa.Boolean(), nullable=True),
    sa.Column('score_technical', sa.Float(), nullable=True),
    sa.Column('score_experience', sa.Float(), nullable=True),
    sa.Column('score_jd_similarity', sa.Float(), nullable=True),
    sa.Column('score_projects', sa.Float(), nullable=True),
    sa.Column('score_education', sa.Float(), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.Column('tier', sa.String(), nullable=True),
    sa.Column('scoring_weights', sa.JSON(), nullable=True),
    sa.Column('report', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['mandate_id'], ['mandates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidate_evaluations')
    op.drop_table('analysis_runs')
    op.drop_index(op.f('ix_mandates_recruiter_id'), table_name='mandates')
    op.drop_table('mandates')
    op.drop_table('document_chunks')
    op.drop_table('candidates')
    # ### end Alembic commands ###
